openapi: 3.0.1
info:
  title: IT-Wallet User UAT - IO App v1
  description: REST APIs consumed by IO App
  version: v1
paths:
  "/nonce":
    get:
      summary: GetNonce
      description: Returns a randomly generated nonce
      operationId: getNonce
      responses:
        "200":
          description: Nonce successfully generated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NonceDetailView"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
  "/wallet-instances":
    post:
      summary: CreateWalletInstance
      description: Create a wallet instance
      operationId: createWalletInstance
      parameters:
        - $ref: "#/components/parameters/XUserHeader"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateWalletInstanceBody"
            example:
              challenge: string
              key_attestation: string
              hardware_key_tag: string
              is_renewal: true
      responses:
        "204":
          description: Wallet instance successfully created
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
  "/wallet-attestations":
    post:
      summary: CreateWalletAttestation
      description: Create and return a Wallet Attestation
      operationId: createWalletAttestation
      parameters:
        - $ref: "#/components/parameters/XUserHeader"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateWalletAttestationBody"
      responses:
        "200":
          description: List of generated Wallet Attestations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletAttestationsView"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
  "/wallet-instances/current/status":
    get:
      summary: GetCurrentWalletInstanceStatus
      description: Retrieve the current Wallet Instance status
      operationId: getCurrentWalletInstanceStatus
      parameters:
        - $ref: "#/components/parameters/XUserHeader"
      responses:
        "200":
          description: Wallet Instance status successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletInstanceData"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
  "/wallet-instances/{id}/status":
    get:
      summary: GetWalletInstanceStatus
      description: Retrieve a Wallet Instance status
      operationId: getWalletInstanceStatus
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - $ref: "#/components/parameters/XUserHeader"
      responses:
        "200":
          description: Wallet Instance status successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletInstanceData"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
    put:
      summary: SetWalletInstanceStatus
      description: |
        Revoke the Wallet Instance associated with the authenticated user.
        If the Wallet Instance is already revoked, the operation will succeed.
      operationId: setWalletInstanceStatus
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - $ref: "#/components/parameters/XUserHeader"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetWalletInstanceStatusData"
      responses:
        "204":
          description: Wallet Instance status successfully set
        "400":
          $ref: "#/components/responses/BadRequest"
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
  "/health":
    get:
      summary: HealthCheck
      description: Used to check if the function is healthy
      operationId: healthCheck
      responses:
        "200":
          description: The function is health
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: string
        "500":
          $ref: "#/components/responses/InternalServerError"
  "/whitelisted-fiscal-code":
    get:
      summary: IsFiscalCodeWhitelisted
      description: Used to check if the fiscal code is in the whitelist
      operationId: isFiscalCodeWhitelisted
      parameters:
        - $ref: "#/components/parameters/XUserHeader"
      responses:
        "200":
          description: Returned when no issues were found in either case (fiscal code
            whitelisted, or not)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WhitelistedFiscalCodeData"
        "400":
          $ref: "#/components/responses/BadRequest"
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
  "/wallet-instance-attestations":
    post:
      summary: CreateWalletInstanceAttestation
      description: Create and return a Wallet Instance Attestation (WIA)
      operationId: createWalletInstanceAttestation
      parameters:
        - $ref: "#/components/parameters/XUserHeader"
      requestBody:
        content:
          application/jwt:
            schema:
              $ref: "#/components/schemas/CreateWalletInstanceAttestationBody"
      responses:
        "200":
          description: Wallet Instance Attestation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletInstanceAttestation"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"

components:
  schemas:
    XUser:
      type: string
    SetWalletInstanceStatusData:
      required:
      - status
      type: object
      properties:
        status:
          enum:
          - REVOKED
          type: string
      example:
        status: REVOKED
    WalletInstanceData:
      required:
      - id
      - is_revoked
      type: object
      properties:
        id:
          type: string
        is_revoked:
          type: boolean
        revocation_reason:
          $ref: "#/components/schemas/RevocationReason"
      description: Describes the status of the wallet.
      example:
        id: string
        is_revoked: true
        revocation_reason: CERTIFICATE_REVOKED_BY_ISSUER
    NonceDetailView:
      required:
      - nonce
      type: object
      properties:
        nonce:
          type: string
    WalletAttestationsView:
      required:
      - wallet_attestations
      type: object
      properties:
        wallet_attestations:
          maxItems: 2
          minItems: 2
          type: array
          items:
            required:
            - format
            - wallet_attestation
            type: object
            properties:
              format:
                enum:
                - jwt
                - dc+sd-jwt
                type: string
              wallet_attestation:
                type: string
    WalletInstanceAttestation:
      required:
      - wallet_instance_attestation
      type: object
      properties:
        wallet_instance_attestation:
          type: string
      example:
        wallet_instance_attestation: string
    CreateWalletInstanceBody:
      required:
      - challenge
      - key_attestation
      - hardware_key_tag
      type: object
      properties:
        challenge:
          minLength: 1
          type: string
          format: binary
        key_attestation:
          minLength: 1
          type: string
          format: binary
        hardware_key_tag:
          minLength: 1
          type: string
      example:
        challenge: string
        key_attestation: string
        hardware_key_tag: string
        is_renewal:
          type: boolean
          default: false
    CreateWalletInstanceAttestationBody:
      type: string
      minLength: 1
      example: eyJhbGciOiJFUzI1NiIsImtpZCI6InZiZVhKa3NNNDV4cGh0QU5uQ2lHNm1DeXVVNGpmR056b3BHdUt2b2dnOWMiLCJ0eXAiOiJ3YXIrand0In0.eyJpc3MiOiJodHRwczovL3dhbGxldC1wcm92aWRlci5leGFtcGxlLm9yZy9pbnN0YW5jZS92YmVYSmtzTTQ1eHBodEFObkNpRzZtQ3l1VTRqZkdOem9wR3VLdm9nZzljIiwic3ViIjoiaHR0cHM6Ly93YWxsZXQtcHJvdmlkZXIuZXhhbXBsZS5vcmcvIiwiY2hhbGxlbmdlIjoiNmVjNjkzMjQtNjBhOC00ZTViLWE2OTctYTc2NmQ4NTc5MGVhIiwiaGFyZHdhcmVfc2lnbmF0dXJlIjoiS29aSWh2Y05BUWNDb0lBd2dBSUIuLi5yZWRhY3RlZCIsImludGVncml0eV9hc3NlcnRpb24iOiJvMk5tYlhSdllYQndiR1V0WVhCd1lYLi4ucmVkYWN0ZWQiLCJoYXJkd2FyZV9rZXlfdGFnIjoiV1FoeUR5bUZLc1A5NWlGcXB6ZEVEV1c0bDdhVm5hMkZuNEpDZVdIWXRiVT0iLCJjbmYiOnsiandrIjp7ImNydiI6IlAtMjU2Iiwia3R5IjoiRUMiLCJ4IjoiNEhOcHRJLXhyMnBqeVJKS0dNbno0V21kblFEX3VKU3E0Ujk1Tmo5OGI0NCIsInkiOiJMSVpuU0IzOXZGSmhZZ1MzazdqWEU0cjMtQ29HRlF3WnRQQklScXBObHJnIiwia2lkIjoidmJlWEprc000NXhwaHRBTm5DaUc2bUN5dVU0amZHTnpvcEd1S3ZvZ2c5YyJ9fSwidnBfZm9ybWF0c19zdXBwb3J0ZWQiOnsiand0X3ZjX2pzb24iOnsiYWxnX3ZhbHVlc19zdXBwb3J0ZWQiOlsiRVMyNTZLIiwiRVMzODQiXX0sImp3dF92cF9qc29uIjp7ImFsZ192YWx1ZXNfc3VwcG9ydGVkIjpbIkVTMjU2SyIsIkVkRFNBIl19fSwiaWF0IjoxNjg2NjQ1MTE1LCJleHAiOjE2ODY2NTIzMTV9.F32bisVth4eDdGxDjB9ByENT-oZLtSY_89uwTSePo2GMEKaeEedpXZE_9mrX7t0_Fmc5m6LNVvIIBqotqsYJYQ
    CreateWalletAttestationBody:
      required:
      - assertion
      type: object
      properties:
        assertion:
          minLength: 1
          type: string
          format: binary
      example:
        assertion: eyJhbGciOiJFUzI1NiIsImtpZCI6InZiZVhKa3NNNDV4cGh0QU5uQ2lHNm1DeXVVNGpmR056b3BHdUt2b2dnOWMiLCJ0eXAiOiJ3YXIrand0In0.eyJpc3MiOiJodHRwczovL3dhbGxldC1wcm92aWRlci5leGFtcGxlLm9yZy9pbnN0YW5jZS92YmVYSmtzTTQ1eHBodEFObkNpRzZtQ3l1VTRqZkdOem9wR3VLdm9nZzljIiwic3ViIjoiaHR0cHM6Ly93YWxsZXQtcHJvdmlkZXIuZXhhbXBsZS5vcmcvIiwiY2hhbGxlbmdlIjoiNmVjNjkzMjQtNjBhOC00ZTViLWE2OTctYTc2NmQ4NTc5MGVhIiwiaGFyZHdhcmVfc2lnbmF0dXJlIjoiS29aSWh2Y05BUWNDb0lBd2dBSUIuLi5yZWRhY3RlZCIsImludGVncml0eV9hc3NlcnRpb24iOiJvMk5tYlhSdllYQndiR1V0WVhCd1lYLi4ucmVkYWN0ZWQiLCJoYXJkd2FyZV9rZXlfdGFnIjoiV1FoeUR5bUZLc1A5NWlGcXB6ZEVEV1c0bDdhVm5hMkZuNEpDZVdIWXRiVT0iLCJjbmYiOnsiandrIjp7ImNydiI6IlAtMjU2Iiwia3R5IjoiRUMiLCJ4IjoiNEhOcHRJLXhyMnBqeVJKS0dNbno0V21kblFEX3VKU3E0Ujk1Tmo5OGI0NCIsInkiOiJMSVpuU0IzOXZGSmhZZ1MzazdqWEU0cjMtQ29HRlF3WnRQQklScXBObHJnIiwia2lkIjoidmJlWEprc000NXhwaHRBTm5DaUc2bUN5dVU0amZHTnpvcEd1S3ZvZ2c5YyJ9fSwidnBfZm9ybWF0c19zdXBwb3J0ZWQiOnsiand0X3ZjX2pzb24iOnsiYWxnX3ZhbHVlc19zdXBwb3J0ZWQiOlsiRVMyNTZLIiwiRVMzODQiXX0sImp3dF92cF9qc29uIjp7ImFsZ192YWx1ZXNfc3VwcG9ydGVkIjpbIkVTMjU2SyIsIkVkRFNBIl19fSwiaWF0IjoxNjg2NjQ1MTE1LCJleHAiOjE2ODY2NTIzMTV9.F32bisVth4eDdGxDjB9ByENT-oZLtSY_89uwTSePo2GMEKaeEedpXZE_9mrX7t0_Fmc5m6LNVvIIBqotqsYJYQ
    RevocationReason:
      enum:
      - CERTIFICATE_REVOKED_BY_ISSUER
      - NEW_WALLET_INSTANCE_CREATED
      - WALLET_INSTANCE_RENEWAL
      - REVOKED_BY_USER
      type: string
    ProblemJson:
      type: object
      properties:
        type:
          type: string
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          format: uri
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: "A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable"
        status:
          maximum: 600
          exclusiveMaximum: true
          minimum: 100
          type: integer
          description: The HTTP status code generated by the origin server for this
            occurrence of the problem.
          format: int32
          example: 500
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
        instance:
          type: string
          description: An absolute URI that identifies the specific occurrence of
            the problem. It may or may not yield further information if dereferenced.
          format: uri
    WhitelistedFiscalCodeData:
      required:
      - whitelisted
      - fiscalCode
      type: object
      properties:
        whitelisted:
          type: boolean
          description: Boolean value that specifies whether the tax code is whitelisted
            or not.
        whitelistedAt:
          type: string
          description: |-
            Date, expressed in ISO 8601 format, when the fiscal code was added to the whitelist.
            Only present if the fiscal code is whitelisted.
        fiscalCode:
          type: string
          description: The fiscal code, the same one passed in input.
      example:
        whitelisted: true
        whitelistedAt: string
        fiscalCode: string
  responses:
    Forbidden:
      description: The server understands the request but refuses to authorize it
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    BadRequest:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    Conflict:
      description: There has been a conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    UnprocessableContent:
      description: Unprocessable Content
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"

  parameters:
    XUserHeader:
      name: x-user
      in: header
      required: true
      schema:
        $ref: "#/components/schemas/XUser"
